// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkBSvpj-iSVIrjkJRZ3omOOoy_BFznCBA',
    appId: '1:556227338507:web:4ebd4c42075007dcef820e',
    messagingSenderId: '556227338507',
    projectId: 'gross-ec4ea',
    authDomain: 'gross-ec4ea.firebaseapp.com',
    storageBucket: 'gross-ec4ea.firebasestorage.app',
    measurementId: 'G-4QHZMEF8TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1t5mY5iiUtNSUUl0baeAqNqfpYpCZ-rw',
    appId: '1:556227338507:android:321fa7787ff06115ef820e',
    messagingSenderId: '556227338507',
    projectId: 'gross-ec4ea',
    storageBucket: 'gross-ec4ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn5_HGz2U3Hsg1awUN5gBVoAUyerG856U',
    appId: '1:556227338507:ios:2764c6f42775137cef820e',
    messagingSenderId: '556227338507',
    projectId: 'gross-ec4ea',
    storageBucket: 'gross-ec4ea.firebasestorage.app',
    iosBundleId: 'com.example.gross',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn5_HGz2U3Hsg1awUN5gBVoAUyerG856U',
    appId: '1:556227338507:ios:2764c6f42775137cef820e',
    messagingSenderId: '556227338507',
    projectId: 'gross-ec4ea',
    storageBucket: 'gross-ec4ea.firebasestorage.app',
    iosBundleId: 'com.example.gross',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkBSvpj-iSVIrjkJRZ3omOOoy_BFznCBA',
    appId: '1:556227338507:web:e7f3eb1d9b6c471aef820e',
    messagingSenderId: '556227338507',
    projectId: 'gross-ec4ea',
    authDomain: 'gross-ec4ea.firebaseapp.com',
    storageBucket: 'gross-ec4ea.firebasestorage.app',
    measurementId: 'G-FV4F6GW0J9',
  );
}
